import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f8",
        foreground: "#1c1b1b",
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#5d3f3e",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#916e6d",
        "outline-variant": "#e6bdbb",
        "surface-tint": "#bf0029",
        primary: "#b90027",
        "on-primary": "#ffffff",
        "primary-container": "#e31837",
        "on-primary-container": "#fffaf9",
        "inverse-primary": "#ffb3b1",
        secondary: "#845400",
        "on-secondary": "#ffffff",
        "secondary-container": "#feb246",
        "on-secondary-container": "#6f4600",
        tertiary: "#00693e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#008550",
        "on-tertiary-container": "#f1fff2",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b1",
        "on-primary-fixed": "#410007",
        "on-primary-fixed-variant": "#92001d",
        "secondary-fixed": "#ffddb6",
        "secondary-fixed-dim": "#ffb95a",
        "on-secondary-fixed": "#2a1800",
        "on-secondary-fixed-variant": "#643f00",
        "tertiary-fixed": "#8df8b7",
        "tertiary-fixed-dim": "#70db9d",
        "on-tertiary-fixed": "#002110",
        "on-tertiary-fixed-variant": "#00522f",
      },
      fontFamily: {
        heading: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      spacing: {
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "container-mobile": "20px",
        "container-desktop": "80px",
        gutter: "24px",
        base: "8px",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      boxShadow: {
        card: "0 4px 20px rgba(0,0,0,0.05)",
        float: "0 10px 30px rgba(227,24,55,0.1)",
      },
      animation: {
        "spin-soft": "spin 3s linear infinite",
        float: "subtle-float 3s ease-in-out infinite",
      },
      keyframes: {
        "subtle-float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
